# Generated by Django 5.2.13 on 2026-05-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_created_at_report_latitude_report_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='report',
            name='issue_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='severity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
