# Generated by Django 5.2.13 on 2026-05-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_image_report_issue_type_report_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
